apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinel.fullname" . }}-env
type: Opaque
data:
  # Helm will automatically base64 encode your key from values.yaml
  FINNHUB_API_KEY: {{ .Values.env.FINNHUB_API_KEY | b64enc | quote }}