apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel.fullname" . }}
  labels:
    app: sentinel
spec:
  # ClusterIP is best for internal apps.
  # If you want to access this from your Mac terminal, we'll use port-forwarding later.
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: sentinel